version: "3.5"

services:

  # https://hub.docker.com/r/linuxserver/transmission
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      PUID: ${PID}
      PGID: ${GID}
      TZ: ${TZ}
      TRANSMISSION_WEB_HOME: /combustion-release/
    volumes:
      - ./config/transmission:/config
      - ./downloads:/downloads
      - ./downloads:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/bazarr
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      PUID: ${PID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ./config/bazarr:/config
      - ./media/movies:/movies
      - ./media/tv:/tv
    ports:
      - 6767:6767
    networks:
      - default
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/sonarr
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      PUID: ${PID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ./config/sonarr:/config
      - ./media/tv:/tv
      - ./downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/radarr
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      PUID: ${PID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ./config/radarr:/config
      - ./media/movies:/movies
      - ./downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/lidarr
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      PUID: ${PID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ./config/lidarr:/config
      - ./media/music:/music
      - ./downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/jackett
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      PUID: ${PID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ./config/jackett:/config
      - ./downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  # https://hub.docker.com/r/lsiocommunity/organizr
  organizr:
    image: lsiocommunity/organizr
    container_name: organizr
    environment:
      PUID: ${PID}
      PGID: ${GID}
    volumes:
      - ./config/organizr:/config
    ports:
      - 12345:80
    restart: unless-stopped

  # https://github.com/containrrr/watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      TZ: ${TZ}
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${SLACK}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro
    restart: unless-stopped
    command: --interval 300 --cleanup

  portainer:
    image: portainer/portainer
    container_name: portainer
    environment:
      PUID: ${PID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
     - ./config/portainer:/data
     - /var/run/docker.sock:/var/run/docker.sock
    ports:
     - 9000:9000
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/plex/
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      PUID: ${PID}
      PGID: ${GID}
      VERSION: docker
    volumes:
      - ./config/plex:/config
      - ./media/tv:/data/tvshows
      - ./media/movies:/data/movies
      - ./media/music:/data/music
      - ./transcode:/transcode
    ports:
      - '32400:32400'
      - '32400:32400/udp'
      - '32469:32469'
      - '32469:32469/udp'
      - '5353:5353/udp'
      - '1900:1900/udp'
    restart: unless-stopped

  # https://github.com/tom472/mediabox/blob/master/docker-compose.yml
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    environment:
      PUID: ${PID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ./config/tautulli:/config
      - ./config/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    ports:
      - 8181:8181
    depends_on:
      - plex
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/ombi
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      PUID: ${PID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ./config/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  # https://github.com/tom472/mediabox/blob/master/docker-compose.yml
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: ${HOSTNAME:-org.zois.docker.olympus}
    environment:
      PGID: ${GID}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
      - SYS_PTRACE
    ports:
      - 19999:19999
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/duplicati
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      PUID: ${PID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ./config/duplicati:/config
      - ./backups:/backups
      - ./config:/source
    ports:
      - 8200:8200
    restart: unless-stopped
